apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
  labels:
    app: jenkins
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jenkins
    template:
      metadata:
        labels:
          app: jenkins
      spec:
      containers:
      - name: jenkins
        image: jenkins:2.60.1-alpine
        imagePullPolicy: IfNotPresent
        securityContext:                     
          runAsUser: 0    
          privileged: true
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-deployment
spec:
  selector:
    app: jenkins
  ports:
  - name: jenkins
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort